services:
  asterisk:
    build: .
    container_name: asterisk
    ports:
      - "${SIP_PORT}:5060/udp"
      - "${SIP_TLS_PORT}:5061/tcp"
      - "${RTP_PORT_RANGE}"
      - "${AMI_PORT}:5038"
      - "${ARI_PORT}:8088"
      - "${WEBRTC_PORT}:8089"
    volumes:
      - ./configs:/etc/asterisk
      - ./odbc/odbc.ini:/etc/odbc.ini
      - ./logs:/var/log/asterisk
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: asterisk-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

